dist: xenial

branches:
  only:
    - master
    - /.*-runci$/

matrix:
  include:
    - language: ruby

      rvm: 2.6.2

      cache:
        directories:
          - ./server/vendor/bundle
      services:
        - postgresql

      before_install:
        - cd server
        - cp config/database.ci.yml config/database.yml
        - cp config/credentials.yml.ci.enc config/credentials.yml.enc
        - sudo apt-get install -y libidn11-dev imagemagick

      install:
        - bundle install --jobs=4 --retry=3 --path vendor/bundle

      before_script:
        - bundle exec rake db:create db:schema:load

      script:
        - bundle exec rake spec
        - bundle exec rubocop

    - language: node_js

      node_js: 10.15.3

      cache:
        directories:
          - ./web/node_modules

      before_install:
        - cd web

      install:
        - yarn install

      script:
        - yarn eslint
        - yarn stylelint
        - yarn testci
