dist: xenial

language: ruby
rvm:
  - 2.6.1

branches:
  only:
    - master
    - /.*-runci$/

cache:
  directories:
    - ./server/vendor/bundle
    - ./web/node_modules
    - $HOME/.nvm

addons:
  postgresql: "10"

before_install:
  - nvm install --lts=dubnium
  - node --version
  - cp deploy/dev/Makefile.test Makefile

install:
  - make install

before_script:
  - psql -c 'create database fsocial_test;' -U postgres
  - cp server/config/travis.database.yml server/config/database.yml
  - cp server/config/travis.credentials.yml.enc server/config/credentials.yml.enc
  - make db

script:
  - make test_web
  - make test_server
