dist: xenial

language: ruby
rvm:
  - 2.6.2

branches:
  only:
    - master
    - /.*-runci$/

cache:
  directories:
    - $HOME/.rvm/
    - $HOME/.nvm
    - ./server/vendor/bundle
    - ./web/node_modules

services:
  - postgresql

before_install:
  - nvm install --lts=dubnium
  - node --version
  - sudo apt-get install -y libidn11-dev imagemagick
  - cp deploy/dev/Makefile.test Makefile

install:
  - make install

before_script:
  - cp server/config/travis.database.yml server/config/database.yml
  - cp server/config/travis.credentials.yml.enc server/config/credentials.yml.enc
  - make db

script:
  - make test_web
  - make test_server
