version: "3.7"
services:
  proxy:
    build:
      context: proxy
    env_file:
      - .env
    restart: always
    command: ["nginx", "-g", "daemon off;"]
    volumes:
      - ./proxy/fsocial.conf:/etc/nginx/conf.d/default.conf
      - ./tmp/nginx/log:/var/log/nginx
      - ./web/public:/var/www/public
    ports:
      - 6006:80
    depends_on:
      - web
      - server

  web:
    build:
      context: web
    env_file:
      - .env
    command: yarn start
    restart: always
    volumes:
      - ./web:/usr/src/app
    ports:
      - 6007:43000

  server:
    build:
      context: server
    env_file:
      - .env
    command: rails s
    tty: true
    stdin_open: true
    restart: always
    depends_on:
      - db
    volumes:
      - ./server:/usr/src/app
    ports:
      - 6008:3000

  db:
    image: postgres:10.6-alpine
    env_file:
      - .env
    ports:
      - 6009:5432
    volumes:
      - ./tmp/postgresql/data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:5.0.3-alpine
    env_file:
      - .env
    restart: always
    volumes:
      - ./tmp/redis/data:/data
    ports:
      - 6005:6379

  portainer:
    image: portainer/portainer
    env_file:
      - .env
    command: -H unix:///var/run/docker.sock --no-auth
    ports:
      - 6000:9000
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tmp/portainer/data:/data

  pgadmin:
    image: dpage/pgadmin4:latest
    volumes:
      - ./tmp/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@framgia.com
      PGADMIN_DEFAULT_PASSWORD: 1111
    ports:
      - 6001:80
    depends_on:
      - db
