version: "3.7"
services:
  proxy:
    build:
      context: proxy
    env_file:
      - .env
    restart: always
    command: ["nginx", "-g", "daemon off;"]
    volumes:
      - ./proxy/fsocial.conf:/etc/nginx/conf.d/default.conf
      - ./tmp/nginx/log:/var/log/nginx
    ports:
      - 3333:80
    depends_on:
      - web
      - server

  web:
    build:
      context: web
    env_file:
      - .env
    command: yarn start
    restart: always
    volumes:
      - ./web:/usr/src/app
    ports:
      - 1234:43000

  server:
    build:
      context: server
    env_file:
      - .env
    command: rails s
    tty: true
    stdin_open: true
    restart: always
    depends_on:
      - db
    volumes:
      - ./server:/usr/src/app
    ports:
      - 4321:3000

  db:
    image: postgres:10.6-alpine
    env_file:
      - .env
    volumes:
      - ./tmp/postgresql/data:/var/lib/postgresql/data
    restart: always

  portainer:
    image: portainer/portainer
    env_file:
      - .env
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tmp/portainer/data:/data
