.PHONY: install db test_web test_server

.DEFAULT_GOAL := test

install:
	cd server && bundle install --deployment --without development production --jobs=3 --retry=3
	cd web && yarn

db:
	cd server && bundle exec rake db:create db:schema:load

test_web:
	cd web && yarn testci && yarn eslint && yarn stylelint

test_server:
	cd server && bundle exec rake spec && bundle exec rubocop
