version: 2
jobs:
  test-web:
    docker:
      - image: circleci/node:dubnium
    working_directory: ~/fsocial
    steps:
      - checkout

      - restore_cache:
          keys:
            - fsocial-dependencies-{{ checksum "yarn.lock" }}
            - fsocial-dependencies-

      - run:
          name: Install dependencies
          command: |
            cd web
            yarn install

      - save_cache:
          paths:
            - ./web/node_modules
          key: fsocial-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: run web tests
          command: |
            cd web
            yarn testci
            yarn eslint
            yarn stylelint
            yarn flow

  test-server:
    docker:
      - image: circleci/ruby:2.6.2
      - image: circleci/postgres:alpine

    working_directory: ~/fsocial

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - fsocial-dependencies-{{ checksum "Gemfile.lock" }}
            - fsocial-dependencies-

      - run:
          name: Install system dependencies
          command: sudo apt-get install -y libidn11-dev imagemagick

      - run:
          name: install dependencies
          command: |
            cd server
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./server/vendor/bundle
          key: fsocial-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run:
          name: copy test configs
          command: |
            cd server
            cp config/travis.database.yml config/database.yml
            rake db:create
            rake db:schema:load

      # run tests
      - run:
          name: run tests server
          command: |
            cd server
            rubocop
            rake spec

workflows:
  version: 2
  workflow:
    jobs:
      - test-web
      - test-server
