default: &default
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>

development:
  <<: *default
  adapter: redis

test:
  <<: *default
  adapter: async

production:
  <<: *default
  adapter: redis
  channel_prefix: fsocial_production
