default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>

development:
  <<: *default
  database: fsocial_development

test:
  <<: *default
  database: fsocial_test

production:
  <<: *default
  database: fsocial_production

staging:
  <<: *default
  database: fsocial_staging
