http:
  statuses:
    errors:
      default: 500
      active_record/record_invalid: 422
      active_record/record_not_found: 404
      application_controller/guest_only: 403
      pundit/not_authorized_error: 403
      application_controller/unauthenticated: 401
      application_controller/not_implemented_yet: 400
      action_controller/parameter_missing: 400
      users/follow/cannot_follow_yourself: 400
      users/follow/already_followed: 400
      users/unfollow/cannot_unfollow_yourself: 400
      users/unfollow/not_followed_yet: 400
    created: 201
    success: 200
    deleted: 204
    updated:
      success: 200
      no_changes: 304
