http:
  statuses:
    errors:
      default: 500
      active_record/record_invalid: 422
      active_record/record_not_found: 404
      application_controller/guest_only: 403
      pundit/not_authorized_error: 403
      application_controller/unauthenticated: 401
      application_controller/not_implemented_yet: 400
      action_controller/parameter_missing: 400
    created: 201
    success: 200
