source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.2'

gem 'active_model_serializers'
gem 'activerecord-import'
gem 'api-pagination'
gem 'bcrypt'
gem 'bootsnap', require: false
gem 'config'
gem 'draper'
gem 'enumerize'
gem 'faker'
gem 'friendly_id'
gem 'google-cloud-vision'
gem 'jwt'
gem 'kaminari'
gem 'mini_magick'
gem 'paranoia'
gem 'pg'
gem 'puma'
gem 'pundit'
gem 'rack-cors'
gem 'rails', '~> 5.2.3'
gem 'rails-i18n'
gem 'ransack'
gem 'redis'
gem 'twitter-text'

group :development, :test do
  gem 'action-cable-testing'
  gem 'bullet'
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'database_cleaner'
  gem 'factory_bot_rails'
  gem 'rspec-rails'
  gem 'rubocop', require: false
end

group :development do
  gem 'listen'
  gem 'spring'
  gem 'spring-watcher-listen'
end

group :test do
  gem 'json-schema'
  gem 'rack-vcr'
  gem 'webmock'
end
