version: '3.7'
services:
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock --no-auth
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /app/fsocial/portainer/data:/data

  db:
    image: postgres:10.6-alpine
    env_file:
      - .env
    volumes:
      - /app/fsocial/postgresql/data:/var/lib/postgresql/data
    restart: always

  web:
    build:
      context: web
    env_file:
      - .env
    command: ['nginx', '-g', 'daemon off;']
    volumes:
      - ./web/build:/usr/src/app
      - ./web/web.conf:/etc/nginx/conf.d/default.conf
    restart: always

  server:
    build:
      context: server
    env_file:
      - .env
    volumes:
      - ./server:/usr/src/app
      - /app/fsocial/rails/log:/usr/src/app/log
      - /app/fsocial/rails/storage:/usr/src/app/storage
    command: puma -C config/puma.rb
    restart: always
    depends_on:
      - db

  proxy:
    build:
      context: proxy
    env_file:
      - .env
    volumes:
      - ./proxy/fsocial.conf:/etc/nginx/conf.d/default.conf
      - ./tmp/.htpasswd:/etc/auth/.htpasswd
      - /app/fsocial/nginx/log:/var/log/nginx
    ports:
      - 80:80
    depends_on:
      - portainer
      - server
      - web
    restart: always
