FROM ruby:2.6.2

RUN apt-get update -qq && apt-get install -y nodejs postgresql-client vim imagemagick libidn11-dev

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY Gemfile* ./
RUN bundle install --without development test

EXPOSE 3000
