version: "3.7"
services:
  web:
    image: moonlight8978/fsocial:web
    build:
      context: web
    env_file:
      - .env

  server:
    image: moonlight8978/fsocial:server
    build:
      context: server
    env_file:
      - .env

  proxy:
    image: moonlight8978/fsocial:proxy
    build:
      context: proxy
    env_file:
      - .env
