FROM ruby:2.6.1-alpine3.9

RUN apk update && apk add -u build-base nodejs tzdata postgresql-dev imagemagick libidn-dev

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY Gemfile* ./
RUN bundle install --without development test

EXPOSE 3000
