version: "3.7"
services:
  web:
    build:
      context: web
    env_file:
      - .env
    command: ["nginx", "-g", "daemon off;"]
    volumes:
      - ./web:/usr/src/app
      - ./web/web.conf:/etc/nginx/conf.d/default.conf
    restart: always
